<?php
/**
 * Shield Job Portal - Database Configuration File
 * Auto-generated by install.php or configured manually.
 */

if (!defined('SHIELD_APP')) {
    define('SHIELD_APP', true);
}

// Database Credentials
define('DB_HOST', 'localhost');
define('DB_PORT', '3306');
define('DB_NAME', 'shield_job_portal');
define('DB_USER', 'root');
define('DB_PASS', '');

// Environment & App Base
define('APP_ENV', 'production'); // 'development' or 'production'
define('APP_SECRET', 'shield_portal_sec_token_' . md5(__DIR__));
define('UPLOAD_DIR', dirname(__DIR__) . '/uploads/');
define('RESUME_DIR', UPLOAD_DIR . 'resumes/');
define('IMAGE_DIR', UPLOAD_DIR . 'images/');
