<?php
/**
 * Shield Job Portal - 1-Click Web Installer for cPanel / Apache
 */

session_start();

$step = isset($_GET['step']) ? intval($_GET['step']) : 1;
$error = '';
$success = '';

// Check if already installed
if (file_exists(__DIR__ . '/api/config.php')) {
    require_once __DIR__ . '/api/config.php';
    if (defined('DB_NAME') && DB_NAME !== '' && DB_NAME !== 'shield_job_portal' && !isset($_GET['force'])) {
        // Already installed check
    }
}

// ------------------------------------------------------------------------
// Handle Step 2 POST (Database Test & Import)
// ------------------------------------------------------------------------
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['db_setup'])) {
    $dbHost = trim($_POST['db_host'] ?? 'localhost');
    $dbPort = trim($_POST['db_port'] ?? '3306');
    $dbName = trim($_POST['db_name'] ?? '');
    $dbUser = trim($_POST['db_user'] ?? '');
    $dbPass = $_POST['db_pass'] ?? '';
    
    $adminName = trim($_POST['admin_name'] ?? 'Shreekant');
    $adminEmail = strtolower(trim($_POST['admin_email'] ?? 'shreekant@shieldinfrasolutions.in'));
    $adminPhone = trim($_POST['admin_phone'] ?? '+91 9876543210');
    $adminPass = $_POST['admin_pass'] ?? 'Shree#2425@22267';

    if (!$dbName || !$dbUser) {
        $error = 'Please provide Database Name and Database User.';
    } else {
        try {
            // Test connection
            $dsn = "mysql:host={$dbHost};port={$dbPort};dbname={$dbName};charset=utf8mb4";
            $pdo = new PDO($dsn, $dbUser, $dbPass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC
            ]);

            // Read and execute schema.sql
            $sqlFile = __DIR__ . '/schema.sql';
            if (!file_exists($sqlFile)) {
                throw new Exception('schema.sql file not found in root directory.');
            }

            $sqlContent = file_get_contents($sqlFile);
            
            // Execute queries in batches
            $pdo->exec($sqlContent);

            // Update or Insert Admin account with hashed password
            $hashedPass = password_hash($adminPass, PASSWORD_BCRYPT);
            $stmt = $pdo->prepare("INSERT INTO users (id, name, email, phone, password, role, subscription) 
                                   VALUES (1, ?, ?, ?, ?, 'admin', 'Premium') 
                                   ON DUPLICATE KEY UPDATE name = ?, phone = ?, password = ?");
            $stmt->execute([$adminName, $adminEmail, $adminPhone, $hashedPass, $adminName, $adminPhone, $hashedPass]);

            // Ensure upload directories exist
            $uploadDirs = [
                __DIR__ . '/uploads',
                __DIR__ . '/uploads/resumes',
                __DIR__ . '/uploads/images'
            ];
            foreach ($uploadDirs as $dir) {
                if (!is_dir($dir)) {
                    @mkdir($dir, 0755, true);
                }
            }

            // Write api/config.php
            $configContent = "<?php\n"
                . "/**\n * Shield Job Portal - Database Configuration File\n * Generated by install.php on " . date('Y-m-d H:i:s') . "\n */\n\n"
                . "if (!defined('SHIELD_APP')) {\n    define('SHIELD_APP', true);\n}\n\n"
                . "define('DB_HOST', " . var_export($dbHost, true) . ");\n"
                . "define('DB_PORT', " . var_export($dbPort, true) . ");\n"
                . "define('DB_NAME', " . var_export($dbName, true) . ");\n"
                . "define('DB_USER', " . var_export($dbUser, true) . ");\n"
                . "define('DB_PASS', " . var_export($dbPass, true) . ");\n\n"
                . "define('APP_ENV', 'production');\n"
                . "define('APP_SECRET', 'shield_" . bin2hex(random_bytes(16)) . "');\n"
                . "define('UPLOAD_DIR', dirname(__DIR__) . '/uploads/');\n"
                . "define('RESUME_DIR', UPLOAD_DIR . 'resumes/');\n"
                . "define('IMAGE_DIR', UPLOAD_DIR . 'images/');\n";

            file_put_contents(__DIR__ . '/api/config.php', $configContent);

            $step = 3; // Finished step
        } catch (PDOException $e) {
            $error = 'Database Connection Failed: ' . $e->getMessage() . '<br><small>Tip: Verify that you have created the database in cPanel MySQL Database Wizard and assigned user privileges.</small>';
        } catch (Exception $e) {
            $error = 'Installation Error: ' . $e->getMessage();
        }
    }
}

// Pre-flight checks
$phpVersionOk = version_compare(PHP_VERSION, '7.4.0', '>=');
$pdoOk = extension_loaded('pdo');
$pdoMysqlOk = extension_loaded('pdo_mysql');
$fileinfoOk = extension_loaded('fileinfo');
$uploadDirWritable = is_writable(__DIR__) || is_writable(__DIR__ . '/uploads');
$apiDirWritable = is_writable(__DIR__ . '/api');
$allChecksPassed = $phpVersionOk && $pdoOk && $pdoMysqlOk && $fileinfoOk;
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Shield Job Portal - Web Installation Wizard</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@700;900&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
:root{
  --black:#0a0a0c;--black2:#141417;--black3:#1d1d22;
  --red:#c1121f;--gold:#d4af37;--gold-light:#f2d375;
  --green:#7CFC00;--text:#f3ede0;--text-dim:#b9b3a5;--border:#33323a;
}
*{box-sizing:border-box;margin:0;padding:0;}
body{background:var(--black);color:var(--text);font-family:'Inter',sans-serif;min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:30px 20px;}
.install-card{background:linear-gradient(160deg,var(--black2),var(--black3));border:1px solid var(--gold);border-radius:16px;max-width:680px;width:100%;padding:36px;box-shadow:0 24px 60px -12px rgba(0,0,0,.9),0 0 24px -4px rgba(124,252,0,.2);}
.brand{font-family:'Cinzel',serif;font-size:24px;font-weight:900;color:var(--gold-light);text-align:center;margin-bottom:6px;}
.brand span{color:var(--red);}
.subtitle{text-align:center;font-size:12px;letter-spacing:.18em;color:var(--text-dim);text-transform:uppercase;margin-bottom:28px;}
.steps{display:flex;justify-content:space-between;margin-bottom:30px;position:relative;}
.steps::before{content:"";position:absolute;top:14px;left:30px;right:30px;height:2px;background:var(--border);z-index:1;}
.step{display:flex;flex-direction:column;align-items:center;position:relative;z-index:2;font-size:11px;color:var(--text-dim);font-weight:600;}
.step-num{width:30px;height:30px;border-radius:50%;background:var(--black3);border:2px solid var(--border);display:flex;align-items:center;justify-content:center;font-weight:700;margin-bottom:6px;color:var(--text);}
.step.active .step-num{background:var(--gold);color:#241a00;border-color:var(--gold-light);box-shadow:0 0 10px rgba(212,175,55,.5);}
.step.active{color:var(--gold-light);}
.step.done .step-num{background:var(--green);color:#000;border-color:var(--green);box-shadow:0 0 10px rgba(124,252,0,.5);}
.check-row{display:flex;justify-content:space-between;align-items:center;padding:12px 14px;border-bottom:1px solid var(--border);font-size:13px;}
.check-row:last-child{border-bottom:none;}
.status-badge{padding:4px 10px;border-radius:20px;font-size:11px;font-weight:700;}
.status-badge.ok{background:rgba(124,252,0,.15);color:var(--green);border:1px solid var(--green);}
.status-badge.fail{background:rgba(193,18,31,.2);color:#ff8a8a;border:1px solid var(--red);}
.field{margin-bottom:14px;}
.field label{display:block;font-size:11.5px;color:var(--text-dim);margin-bottom:6px;font-weight:600;letter-spacing:.03em;}
.field input{width:100%;padding:11px 14px;border-radius:8px;border:1px solid var(--border);background:#0e0e11;color:var(--text);font-size:13.5px;font-family:'Inter';}
.field input:focus{outline:none;border-color:var(--gold);box-shadow:0 0 0 2px rgba(212,175,55,.25);}
.btn3d{font-family:'Inter',sans-serif;font-weight:700;border:none;cursor:pointer;padding:14px 28px;border-radius:10px;background:linear-gradient(180deg,var(--gold-light),var(--gold) 55%,#a3822a);color:#241a00;box-shadow:0 6px 0 #7a611c,0 10px 18px -4px rgba(124,252,0,.4);width:100%;text-align:center;font-size:14px;transition:all .12s ease;}
.btn3d:hover{filter:brightness(1.06);}
.btn3d:active{transform:translateY(6px);box-shadow:0 0 0 #7a611c;}
.alert{padding:14px 16px;border-radius:8px;margin-bottom:20px;font-size:13px;line-height:1.6;}
.alert.error{background:rgba(193,18,31,.2);border:1px solid var(--red);color:#ffbebe;}
.alert.success{background:rgba(124,252,0,.12);border:1px solid var(--green);color:var(--text);}
.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;}
.section-title{color:var(--gold-light);font-family:'Cinzel',serif;font-size:15px;margin:20px 0 12px;border-bottom:1px solid var(--border);padding-bottom:6px;}
</style>
</head>
<body>

<div class="install-card">
  <div class="brand">SHIELD<span>JOB</span>PORTAL</div>
  <div class="subtitle">cPanel / Apache Web Installation Wizard</div>

  <div class="steps">
    <div class="step <?= $step >= 1 ? ($step > 1 ? 'done' : 'active') : '' ?>">
      <div class="step-num"><?= $step > 1 ? '✓' : '1' ?></div>
      <span>Diagnostics</span>
    </div>
    <div class="step <?= $step >= 2 ? ($step > 2 ? 'done' : 'active') : '' ?>">
      <div class="step-num"><?= $step > 2 ? '✓' : '2' ?></div>
      <span>Database &amp; Admin</span>
    </div>
    <div class="step <?= $step === 3 ? 'done' : '' ?>">
      <div class="step-num"><?= $step === 3 ? '✓' : '3' ?></div>
      <span>Ready!</span>
    </div>
  </div>

  <?php if ($error): ?>
    <div class="alert error"><?= $error ?></div>
  <?php endif; ?>

  <!-- STEP 1: System Diagnostic Checks -->
  <?php if ($step === 1): ?>
    <div style="background:var(--black3);border:1px solid var(--border);border-radius:10px;margin-bottom:24px;">
      <div class="check-row">
        <span>PHP Version (>= 7.4)</span>
        <span class="status-badge <?= $phpVersionOk ? 'ok' : 'fail' ?>"><?= PHP_VERSION ?> <?= $phpVersionOk ? '✓' : '✗' ?></span>
      </div>
      <div class="check-row">
        <span>PDO Extension</span>
        <span class="status-badge <?= $pdoOk ? 'ok' : 'fail' ?>"><?= $pdoOk ? 'Enabled ✓' : 'Disabled ✗' ?></span>
      </div>
      <div class="check-row">
        <span>PDO MySQL Driver</span>
        <span class="status-badge <?= $pdoMysqlOk ? 'ok' : 'fail' ?>"><?= $pdoMysqlOk ? 'Enabled ✓' : 'Disabled ✗' ?></span>
      </div>
      <div class="check-row">
        <span>FileInfo Extension</span>
        <span class="status-badge <?= $fileinfoOk ? 'ok' : 'fail' ?>"><?= $fileinfoOk ? 'Enabled ✓' : 'Disabled ✗' ?></span>
      </div>
      <div class="check-row">
        <span>Uploads Directory</span>
        <span class="status-badge <?= $uploadDirWritable ? 'ok' : 'fail' ?>"><?= $uploadDirWritable ? 'Writable ✓' : 'Check Permissions' ?></span>
      </div>
    </div>

    <?php if ($allChecksPassed): ?>
      <a href="install.php?step=2" class="btn3d" style="display:block;text-decoration:none;">Proceed to Database Setup →</a>
    <?php else: ?>
      <div class="alert error">Please enable the required PHP extensions in your cPanel PHP Selector (Select PHP Version) before proceeding.</div>
    <?php endif; ?>

  <!-- STEP 2: Database Credentials & Admin Account -->
  <?php elseif ($step === 2): ?>
    <form method="POST" action="install.php?step=2">
      <input type="hidden" name="db_setup" value="1">
      
      <div class="section-title">1. MySQL Database Connection</div>
      <p style="color:var(--text-dim);font-size:12px;margin-bottom:14px;">Enter the MySQL database credentials created in your cPanel <b>MySQL® Database Wizard</b>.</p>
      
      <div class="form-grid">
        <div class="field">
          <label>Database Host</label>
          <input type="text" name="db_host" value="localhost" required>
        </div>
        <div class="field">
          <label>Database Port</label>
          <input type="text" name="db_port" value="3306" required>
        </div>
      </div>

      <div class="field">
        <label>Database Name (e.g. cpaneluser_shieldjob)</label>
        <input type="text" name="db_name" placeholder="cpaneluser_shieldjob" required>
      </div>

      <div class="form-grid">
        <div class="field">
          <label>Database User</label>
          <input type="text" name="db_user" placeholder="cpaneluser_dbuser" required>
        </div>
        <div class="field">
          <label>Database Password</label>
          <input type="password" name="db_pass" placeholder="••••••••••••" required>
        </div>
      </div>

      <div class="section-title">2. Administrator Account</div>
      <p style="color:var(--text-dim);font-size:12px;margin-bottom:14px;">Default credentials for full access to CRM, ATS, and site settings.</p>

      <div class="form-grid">
        <div class="field">
          <label>Admin Name</label>
          <input type="text" name="admin_name" value="Shreekant" required>
        </div>
        <div class="field">
          <label>Admin Phone</label>
          <input type="text" name="admin_phone" value="+91 9876543210" required>
        </div>
      </div>

      <div class="field">
        <label>Admin Email</label>
        <input type="email" name="admin_email" value="shreekant@shieldinfrasolutions.in" required>
      </div>

      <div class="field">
        <label>Admin Password</label>
        <input type="password" name="admin_pass" value="Shree#2425@22267" required>
      </div>

      <button type="submit" class="btn3d" style="margin-top:10px;">Run 1-Click Installation &amp; Setup Database</button>
    </form>

  <!-- STEP 3: Installation Complete -->
  <?php elseif ($step === 3): ?>
    <div class="alert success" style="text-align:center;padding:24px;">
      <h3 style="color:var(--green);font-family:'Cinzel',serif;font-size:22px;margin-bottom:10px;">Installation Completed Successfully!</h3>
      <p style="color:var(--text);font-size:14px;line-height:1.7;">
        All database tables have been imported, the Administrator account has been configured, and your application configuration file has been written to <code>api/config.php</code>.
      </p>
    </div>

    <div style="background:var(--black3);border:1px solid var(--border);border-radius:10px;padding:18px;margin-bottom:24px;font-size:13px;">
      <div style="color:var(--gold-light);font-weight:700;margin-bottom:8px;">Admin Login Credentials:</div>
      <div><b>Email:</b> <span style="color:var(--text)"><?= htmlspecialchars($_POST['admin_email'] ?? 'shreekant@shieldinfrasolutions.in') ?></span></div>
      <div><b>Password:</b> <span style="color:var(--text)"><?= htmlspecialchars($_POST['admin_pass'] ?? 'Shree#2425@22267') ?></span></div>
    </div>

    <a href="index.html" class="btn3d" style="display:block;text-decoration:none;">🚀 Launch Shield Job Portal</a>
  <?php endif; ?>

</div>

</body>
</html>
